const dataCodeName = Object.freeze({
	openStoreName: '개통점명',
	bizNoFront: '사업자번호 앞자리',
	bizNoMiddle: '사업자번호 중간자리',
	bizNoBack: '사업자번호 뒷자리',
	chargerPhone: '담당자 연락처',
	returnZipCode: '우편번호',
	returnAddr: '기본주소',
	returnAddrDetail: '상세주소',
	username: '계정명',
	password: '비밀번호',
	phone: '연락처',
	phone1: '연락처 앞자리',
	phone2: '연락처 중간자리',
	phone3: '연락처 뒷자리',
	roleIds: '역할',
	name: '사용자명',
	email: '이메일',
	saleStoreName: '영업점명',
	goodsName: '상품명',
	modelName: '모델명',
	network: '통신망',
	maker: '제조사',
	capacity: '용량',
	chargeAmt: '요금',
	chargeName: '요금제명',
	category: '카테고리',
	addSvcCharge: '요금',
	addSvcName: '부가서비스명',
	addSvcMemo: '메모',
	ceoName: '대표자명',
	chargeCode: '요금코드',
	chargerName: '담당자명',
	chargerEmail: '담당자 이메일',
	chargeId: '요금제',
	goodsId: '기기',
	releaseAmt: '출고가',
	supportAmt: '공시지원금',
	releaseDate: '공시일자',
	provName: '공급처명',
	stockName: '보유처',
	provId: '공급처',
	stockId: '보유처',
	telecom: '통신사',
	addDdctAmt: '추가차감금액',
	ddctAmt: '차감비',
	missProduct: '누락제품',
	productFaultyYn: '제품상태',
	productMissYn: '구성품누락',
	extrrStatus: '외장상태',
	inStockStatus: '입고상태',
	returnStockAmt: '반품비',
	returnStockMemo: '수정메모',
	inStockRegiDate: '입고일',
	returnStockRegiDate: '출고일',
	statusStr: '재고구분',
	makerName: '제조사',
	goodsOptionId: '색상',
	colorName: '색상',
	barcode: '기기 일련번호',
	prevStockId: '이전 보유처',
	nextStockId: '이동처',
	cusName: '고객명',
	cusPhone: '고객 전화번호',
	usimFullBarcode: '유심 일련번호',
	zipCode: '우편번호',
	addr2: '상세주소2',
	courier: '택배사',
	invoiceNo: '송장번호',
	transStoreId: '이관처',
	prov: '공급처',
	stock: '보유처',
	stockType: '재고구분',
	holdPlc: '보유처',
	cusPhone1: '연락처 앞자리',
	cusPhone2: '연락처 중간자리',
	cusPhone3: '연락처 뒷자리',
	chargerPhone1: '연락처 앞자리',
	chargerPhone2: '연락처 중간자리',
	chargerPhone3: '연락처 뒷자리',
	unLockYn: '자급제',
});
export { dataCodeName };
